services:

  web:
    build: .
    container_name: inventory-web
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:8.0
    container_name: inventory-db
    restart: always
    environment:
      MYSQL_DATABASE: inventory_system
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: inventory_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./inventory_system.sql:/docker-entrypoint-initdb.d/inventory_system.sql
    ports:
      - "3306:3306"

volumes:
  mysql_data: